# Generated by Django 4.1.1 on 2022-09-23 04:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0005_product_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(99999999)]),
        ),
    ]
